#!/usr/bin/env python3
"""Regenerate docs/VALIDATION.md by running the engine against published tables.

The document is generated rather than written, so it cannot drift from the code.
If a refactor moves a number, the table says so the next time `make validate`
runs.
"""
from __future__ import annotations

import sys
from datetime import date
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "engine"))

from standbehind.depreciation import (
    FIFTEEN_YEAR,
    FIVE_YEAR,
    RESIDENTIAL_RENTAL,
    SEVEN_YEAR,
    build_schedule,
)
from standbehind.money import Money
from standbehind.rules import load
from standbehind.rules.schema import FilingStatus as FS

BASIS = Money.from_dollars("1000000")
OUT = ROOT / "docs" / "VALIDATION.md"

# IRS Pub 946 Appendix A, as published.
TABLE_A1 = {
    "5-year (200% DB, half-year)":  (FIVE_YEAR,   ["20.00","32.00","19.20","11.52","11.52","5.76"]),
    "7-year (200% DB, half-year)":  (SEVEN_YEAR,  ["14.29","24.49","17.49","12.49","8.93","8.92","8.93","4.46"]),
    "15-year (150% DB, half-year)": (FIFTEEN_YEAR,["5.00","9.50","8.55","7.70","6.93","6.23","5.90","5.90"]),
}
TABLE_A6_YEAR1 = ["3.485","3.182","2.879","2.576","2.273","1.970",
                  "1.667","1.364","1.061","0.758","0.455","0.152"]


def pct(amount: Money, places: str) -> Decimal:
    return (Decimal(amount.cents) / Decimal(BASIS.cents) * 100).quantize(Decimal(places))


def main() -> int:
    failures = 0

    # ---- Table A-6 ----
    a6: list[str] = []
    for month, expected in enumerate(TABLE_A6_YEAR1, start=1):
        s = build_schedule(BASIS, date(2020, month, 1), RESIDENTIAL_RENTAL)
        got = pct(s.by_year[0][1], "0.001")
        ok = got == Decimal(expected)
        failures += 0 if ok else 1
        a6.append(f"| {month:02d} | {expected} | {got} | {'PASS' if ok else 'FAIL'} |")
    s = build_schedule(BASIS, date(2020, 1, 1), RESIDENTIAL_RENTAL)
    mid = pct(s.annual(2022), "0.001")
    mid_ok = mid == Decimal("3.636")
    failures += 0 if mid_ok else 1

    # ---- Table A-1 ----
    a1: list[str] = []
    for label, (cls, published) in TABLE_A1.items():
        s = build_schedule(BASIS, date(2021, 3, 1), cls)
        got = [pct(a, "0.001") for _, a in s.by_year]
        worst = Decimal(0)
        for i, exp in enumerate(published):
            worst = max(worst, abs(got[i] - Decimal(exp)))
        exact = s.total == BASIS
        ok = worst <= Decimal("0.005") and exact
        failures += 0 if ok else 1
        a1.append(
            f"| {label} | {' / '.join(published)} | "
            f"{' / '.join(str(g) for g in got[:len(published)])} | "
            f"{worst} | {'yes' if exact else 'NO'} | {'PASS' if ok else 'FAIL'} |")

    # ---- Bracket arithmetic, computed by hand in the doc ----
    rules = load(2026)
    mfj = rules.ordinary[FS.MARRIED_FILING_JOINTLY]
    hand = [(24800, "0.10"), (100800 - 24800, "0.12"), (211400 - 100800, "0.22"),
            (403550 - 211400, "0.24"), (500000 - 403550, "0.32")]
    hand_total = Money.sum(
        Money.from_dollars(str(a)).apply_rate(Decimal(r)) for a, r in hand)
    engine_total = mfj.tax_on(Money.from_dollars("500000"))
    bracket_ok = hand_total == engine_total
    failures += 0 if bracket_ok else 1

    # ---- Determinism ----
    from standbehind.fixtures import MARKET, build_household, build_strategies
    from standbehind.simulate import simulate
    portfolio, strategies = build_household(), build_strategies()
    runs = [simulate(portfolio, strategies[0], MARKET, start_year=2026, horizon=30)
            for _ in range(3)]
    hashes = {r.ledger_hash for r in runs}
    det_ok = len(hashes) == 1
    failures += 0 if det_ok else 1

    doc = f"""# Validation

Generated by `make validate` (`scripts/validate.py`). Every figure below is
produced by running the engine, so this document cannot drift from the code.

**Result: {'all checks pass' if failures == 0 else f'{failures} FAILURES'}.**

---

## 1. MACRS residential rental, 27.5 years, mid-month

IRS Pub 946 Table A-6, first-year percentage by placed-in-service month.
Published to three decimals; the engine reproduces all twelve **exactly**.

| Month placed in service | Pub 946 | Engine | |
|---|---|---|---|
{chr(10).join(a6)}

Mid-schedule full-year rate: published **3.636%**, engine **{mid}%** — \
{'PASS' if mid_ok else 'FAIL'}.

## 2. MACRS personal property and land improvements

IRS Pub 946 Table A-1. These are published to **two** decimals, and the IRS then
nudges individual years so each column sums to exactly 100.00%. The engine
computes the exact statutory fraction instead, so the two agree to within one
published unit but are not always byte-identical — for example 7-year property
year 6 is exactly 8.925%, which Pub 946 prints as 8.92 rather than 8.93 so the
column lands on 100.00.

The honest test is therefore "within half a published unit, and the schedule sums
to exactly the basis". Asserting byte equality against a rounded presentation
would be testing the rounding, not the depreciation.

The declining-balance-to-straight-line switch year is **computed**, not
hardcoded; reproducing these columns is the evidence it is found correctly.

| Class | Pub 946 Table A-1 | Engine | Worst diff | Sums to basis | |
|---|---|---|---|---|---|
{chr(10).join(a1)}

## 3. Bracket arithmetic

2026 ordinary tax on $500,000 of taxable income, married filing jointly,
computed by hand from Rev. Proc. 2025-32 thresholds:

```
10% x  $24,800              =  $2,480.00
12% x ($100,800 - $24,800)  =  $9,120.00
22% x ($211,400 - $100,800) = $24,332.00
24% x ($403,550 - $211,400) = $46,116.00
32% x ($500,000 - $403,550) = $30,864.00
                              ----------
                              {hand_total}
```

Engine: **{engine_total}** — {'PASS' if bracket_ok else 'FAIL'}.

## 4. Determinism

The same scenario replayed three times must produce a byte-identical ledger hash.

```
{chr(10).join('  ' + r.ledger_hash for r in runs)}
```

{'All three identical' if det_ok else 'HASHES DIVERGED'} — \
{'PASS' if det_ok else 'FAIL'}.

## 5. Invariants held under property-based testing

Asserted by Hypothesis across generated inputs rather than chosen examples
(`make test`):

| Invariant | Where |
|---|---|
| `sum(money.allocate(weights)) == money`, for any amount and any weights | `test_money.py` |
| A depreciation schedule sums to exactly the depreciable basis, for any basis, month and class | `test_depreciation.py` |
| Accumulated depreciation never exceeds depreciable basis | `test_depreciation.py` |
| Every amortising loan reaches a zero balance | `test_loans.py` |
| `recognized_gain + deferred_gain == realized_gain` in every 1031 | `test_exchange_1031.py` |
| Recognised gain never exceeds boot, nor realised gain | `test_exchange_1031.py` |
| The character split sums to the recognised gain | `test_exchange_1031.py` |
| Passive losses are conserved: allowed + suspended == incurred | `test_household.py` |
| A lien payoff waterfall conserves every cent | `test_loans.py` |

## Sources

- IRS Pub 946, *How To Depreciate Property*, Appendix A (Tables A-1, A-6).
- IRS Rev. Proc. 2025-32 (2026 inflation adjustments), cross-checked against the
  Tax Foundation's published 2026 bracket tables.
- IRC §§ 1, 121, 168, 469, 1011–1016, 1031, 1231, 1245, 1250, 1411.
- Treas. Reg. §§ 1.48-1(c), 1.167(a)-2, 1.167(a)-5, 1.168(i)-6, 1.1031(b)-1(c),
  Temp. Reg. § 1.163-8T.
- IRS Form 4797 instructions (line 26a, additional depreciation).
- Rev. Proc. 87-56 asset class 00.3 (land improvements).
- California FTB Form 3840 and the 2025 rate schedules.

Each rule file under `packages/engine/standbehind/rules/` carries its own
`source` and per-field `verified` mapping.
"""
    OUT.write_text(doc)
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"{'ALL CHECKS PASS' if failures == 0 else str(failures) + ' FAILURES'}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
